project:
  title: "Beta model tutorial"
  render:
    - index.qmd
  output-dir: docs

repo-url: https://github.com/jgeller112/beta_regression_tutorial

format:
  html:
    toc: true
    title-block-banner: true
    fontsize: 14pt
    mainfont: Fira Sans
    code-fold: true
    other-links:
      - text: Preprint
        href: todo
        icon: file-pdf
      - text: Online supplement
        href: todo
        icon: globe2
      - text: GitHub Repository
        href: https://github.com/jgeller112/beta_regression_tutorial
        icon: github

execute:
  freeze: auto
