# This file was generated by the {rix} R package v0.15.6 on 2025-06-11
# with following call:
# >rix(date = "2025-04-07",
#  > r_pkgs = required_packages,
#  > system_pkgs = c("quarto",
#  > "git",
#  > "pandoc",
#  > "typst",
#  > "stanc",
#  > "tbb"),
#  > git_pkgs = list(list(package_name = "cmdstanr",
#  > repo_url = "https://github.com/stan-dev/cmdstanr",
#  > commit = "541f36c74c236a322eaa0908e2e86425790ca2cf"),
#  > list(package_name = "ordbetareg_pack",
#  > repo_url = "https://github.com/saudiwin/ordbetareg_pack",
#  > commit = "673292ba8f1b0b0978af8732579f42fc0b37c6ff")),
#  > tex_pkgs = c("amsmath",
#  > "ninecolors",
#  > "apa7",
#  > "scalerel",
#  > "threeparttable",
#  >      "threeparttablex",
#  > "endfloat",
#  > "environ",
#  > "multirow",
#  > "tcolorbox",
#  > "pdfcol",
#  > "tikzfill",
#  > "fontawesome5",
#  > "framed",
#  > "newtx",
#  > "fontaxes",
#  > "xstring",
#  > "wrapfig",
#  > "tabularray",
#  > "siunitx",
#  > "fvextra",
#  > "geometry",
#  > "setspace",
#  > "fancyvrb",
#  > "anyfontsize"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = "Rscript install_cmdstan.R",
#  > r_ver = "4.4.3")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-04-07.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      brms
      collapse
      cowplot
      easystats
      extraDistr
      ggokabeito
      ggrain
      marginaleffects
      patchwork
      posterior
      quarto
      scales
      tidybayes
      tidyverse
      tinytable
      transformr
      viridis;
  };
 
    cmdstanr = (pkgs.rPackages.buildRPackage {
      name = "cmdstanr";
      src = pkgs.fetchgit {
        url = "https://github.com/stan-dev/cmdstanr";
        rev = "541f36c74c236a322eaa0908e2e86425790ca2cf";
        sha256 = "sha256-4qf52WZ50S0PdeKVKe08jvWCegbf9H+QZCyoq7w2Xy4=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          checkmate
          data_table
          jsonlite
          posterior
          processx
          R6
          withr
          rlang;
      };
    });

    ordbetareg_pack = (pkgs.rPackages.buildRPackage {
      name = "ordbetareg_pack";
      src = pkgs.fetchgit {
        url = "https://github.com/saudiwin/ordbetareg_pack";
        rev = "673292ba8f1b0b0978af8732579f42fc0b37c6ff";
        sha256 = "sha256-hqrS4NQ6TNRmGVGEFNNl6RXgAy+JR8M5m0RnFgpZy20=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          brms
          dplyr
          ggplot2
          tidyr
          scales
          stringr
          tibble;
      };
    });
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      anyfontsize
      apa7
      endfloat
      environ
      fancyvrb
      fontawesome5
      fontaxes
      framed
      fvextra
      geometry
      multirow
      newtx
      ninecolors
      pdfcol
      scalerel
      setspace
      siunitx
      tabularray
      tcolorbox
      threeparttable
      threeparttablex
      tikzfill
      wrapfig
      xstring;
  });
  
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      nix
      pandoc
      quarto
      R
      stanc
      tbb
      typst;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ cmdstanr ordbetareg_pack rpkgs tex system_packages   ];
    shellHook = "Rscript install_cmdstan.R";
  }; 
in
  {
    inherit pkgs shell;
  }
