name: Deploy

on:
  workflow_run:
    workflows: ["Render paper with Nix and Quarto"]
    types: [completed]

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    # only deploy on successful renders
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout the exact rendered commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Prepare HTML for deployment
        run: |
          set -euo pipefail
          mkdir -p public
          # HTML -> index.html
          cp manuscript/ms.html public/index.html
          # Optional extras if present
          [ -f manuscript/ms.pdf ] && cp manuscript/ms.pdf public/
          [ -f manuscript/ms.docx ] && cp manuscript/ms.docx public/
          [ -d manuscript/ms_files ] && cp -r manuscript/ms_files public/
          [ -d manuscript/_extensions ] && cp -r manuscript/_extensions public/
          
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
